Add fma3-*.c into PROD_FMA3_MICROKERNEL_SRCS
google/XNNPACK pull request #2603
Opened 2022-02-13 11:11 UTC by mattn

2022-02-13 17:50 UTC, Maratyszcza requested changes
Insert in sorted order

2022-02-14 02:25 UTC, mattn commented
Fixed. Thank you.

2022-02-14 05:39 UTC, Maratyszcza approved these changes

2022-02-14 05:48 UTC, mattn commented
Sorry, OT. I'm very surprised to see TensorFlow Lite SSD with an XNNPACK delegate running at 38fps on my Windows.

https://user-images.githubusercontent.com/10111/153807178-7c900b83-b27b-4233-be13-9a8c6be02c4a.mp4

2022-02-14 08:58 UTC, merged